WebApplication Project_nearlyNew/TermProject_NearlyNew/TermProject_NearlyNew/Controllers/RegistrationController.cs
using System;
using System.Net;
using System.Net.Mail;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TermProject_NearlyNew.Models;
using TermProject_NearlyNew.Models.DAO;
using TermProject_NearlyNew.Models.DTO;


namespace TermProject_NearlyNew.Controllers
{
    public class RegistrationController : Controller
    {


        public static string LoginCode;

        public static Account User { get; set; }

        public static void SendValidationCode(string Code)
        {
            try
            {
                SmtpClient SmtpServer = new SmtpClient();
                SmtpServer.Host = "smtp.gmail.com";
                SmtpServer.Port = 587;
                SmtpServer.Credentials = new NetworkCredential("nearlynewassist@gmail.com", "Password0011");
                SmtpServer.EnableSsl = true;
                SmtpServer.DeliveryMethod = SmtpDeliveryMethod.Network;
                SmtpServer.Timeout = 20000;

                MailMessage mail = new MailMessage();
                mail.From = new MailAddress("nearlynewassist@gmail.com");
                mail.To.Add(User.Email);
                mail.Subject = "2-step Authentication";
                mail.Body = "Your validation code: " + Code;

                SmtpServer.Send(mail);
                Console.WriteLine("Successed");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult AuthenticateOne(Account account)
        {
            if (AccountDAO.GetAccount(account) != null)
            {
                User = AccountDAO.GetAccount(account);
                if (User.Role == "Admin")
                {
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    LoginCode = AccountDAO.RandomCode();
                    SendValidationCode(LoginCode);
                    return View("SecondAuthentication");
                }
            }
            else
            {
                return View("Login");
            }
        }

        public IActionResult AuthenticateTwo(string code)
        {
            if (code == LoginCode)
            {
                return View("Manage", User);
            }
            else
            {
                User = null;
                LoginCode = null;
                return View("Login");
            }
        }

        public IActionResult Manage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateNewAccount(Account account)
        {
            AccountDAO.Create(account);
            return RedirectToAction("Index","Home",AccountDAO.GetAccounts);
        }
    }
}

WebApplication Project_nearlyNew/TermProject_NearlyNew/TermProject_NearlyNew/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en-gb">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>nearlyNew</title>
    <link rel="icon" href="img/favicon.png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <!-- animate CSS -->
    <link rel="stylesheet" href="~/css/animate.css">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="~/css/all.css">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="~/css/slick.css">
    <!-- style CSS -->
    <link rel="stylesheet" href="~/css/style.css">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container-fluid">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-11">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index"> <img src="~/img/logo.png" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Shop
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" asp-controller="Home" asp-action="All_Product"> Shop category</a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Male_Product"> Shop Male</a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Female_Product"> Shop Female</a>

                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_3"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Explore
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                        <a class="dropdown-item" asp-controller="Registration" asp-action="Login">
                                            login

                                        </a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Tracking">tracking</a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Checkout">product checkout</a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="MyCart">shopping cart</a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Confirmation">Confirmation</a>
                                       
                                        <a class="dropdown-item" href="elements.html">elements</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_2"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        FAQ
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Shipping">Shipping</a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Returns">Returns</a>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="Quality">Quality Standards</a>
                                    </div>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex">
                            <div class="dropdown cart">
                                <a class="dropdown-toggle"asp-controller="Home" asp-action="MyCart" id="navbarDropdown3" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="ti-bag"></i>
                                </a>
                                <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <div class="single_product">

                                    </div>
                                </div> -->
                            </div>
                            <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
       <!--  <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div> -->
    </header>
    <!-- Header part end-->
    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"> <img src="~/img/header.jpg" alt="logo"> </a>
        </div>
    </section>
    <!-- banner part start-->
    @RenderBody()
    
    <!--::footer_part start::-->
    <footer class="footer_part">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Category</h4>
                        <ul class="list-unstyled">
                            <li><a asp-controller="Home" asp-action="All_Product">All</a></li>
                            <li><a asp-controller="Home" asp-action="Male_Product">Boys</a></li>
                            <li><a asp-controller="Home" asp-action="Female_Product">Girls</a></li>
                           
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Company</h4>
                        <ul class="list-unstyled">
                            <li><a asp-controller="Home" asp-action="AboutUs">About Us</a></li>
                            <li><a asp-controller="Home" asp-action="Shipping">Shipping Info</a></li>
                            <li><a asp-controller="Home" asp-action="Returns">Returns Info</a></li>
                            <li><a asp-controller="Home" asp-action="Quality">Quality Standard</a></li>

                            </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="single_footer_part">
                        <h4>Address</h4>
                        <ul class="list-unstyled">
                            <li><a href="#">941 Progress Ave, Scarborough, Ontario</a></li>
                            <li><span>contact@nearlynew.com</span></li>
                        </ul>
                    </div>
                </div>
                
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->
    <!-- jquery plugins here-->
    <script src="js/jquery-1.12.1.min.js"></script>
    <!-- popper js -->
    <script src="js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- easing js -->
    <script src="js/jquery.magnific-popup.js"></script>
    <!-- swiper js -->
    <script src="js/swiper.min.js"></script>
    <!-- swiper js -->
    <script src="js/mixitup.min.js"></script>
    <!-- particles js -->
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.nice-select.min.js"></script>
    <!-- slick js -->
    <script src="js/slick.min.js"></script>
    <script src="js/jquery.counterup.min.js"></script>
    <script src="js/waypoints.min.js"></script>
    <script src="js/contact.js"></script>
    <script src="js/jquery.ajaxchimp.min.js"></script>
    <script src="js/jquery.form.js"></script>
    <script src="js/jquery.validate.min.js"></script>
    <script src="js/mail-script.js"></script>
    <!-- custom js -->
    <script src="js/custom.js"></script>
</body>

</html>